'use strict';

/*
 * Fonemas del inglés americano (General American) explicados para hispanohablantes.
 * Ejemplos: 'palabra|transcripción|letras que producen el sonido'
 * nivel: 1 = existe en español, 2 = parecido, 3 = no existe en español (¡a practicar!)
 */
const FONEMAS = [
  // ---------- Vocales cortas y largas ----------
  { s: 'i', g: 'vocal', nombre: 'i larga (tensa)', nivel: 1,
    ej: ['sheep|ʃip|ee', 'see|si|ee', 'eat|it|ea', 'key|ki|ey', 'people|ˈpipəl|eo', 'me|mi|e'],
    grafias: 'ee, ea, e, ie, ey, i (pizza)',
    como: 'Labios estirados como sonriendo, lengua alta y adelante, tensa. Es larga.',
    es: 'Muy parecida a la «i» española de «sí», pero un poco más larga y tensa.',
    error: 'Pronunciarla corta: «sheep» (oveja) se confunde con «ship» (barco).',
    pares: ['sheep/ship', 'seat/sit', 'leave/live', 'eat/it', 'feel/fill'] },
  { s: 'ɪ', g: 'vocal', nombre: 'i corta (relajada)', nivel: 3,
    ej: ['ship|ʃɪp|i', 'sit|sɪt|i', 'big|bɪɡ|i', 'fish|fɪʃ|i', 'milk|mɪlk|i', 'gym|dʒɪm|y'],
    grafias: 'i, y (gym), e (pretty), ui (build)',
    como: 'Boca un poco más abierta que para /i/, lengua relajada y un poco más baja. Corta.',
    es: 'No existe en español. Está entre la «i» y la «e»: di «i» relajando la boca, casi como una «e» cerrada.',
    error: 'Decirla como la «i» española, así «live» (vivir) suena como «leave» (irse).',
    pares: ['ship/sheep', 'sit/seat', 'live/leave', 'it/eat', 'bit/bet'] },
  { s: 'ɛ', g: 'vocal', nombre: 'e abierta', nivel: 1,
    ej: ['bed|bɛd|e', 'red|rɛd|e', 'head|hɛd|ea', 'said|sɛd|ai', 'friend|frɛnd|ie', 'yes|jɛs|e'],
    grafias: 'e, ea (head), ai (said), ie (friend)',
    como: 'Boca medio abierta, lengua adelante en posición media.',
    es: 'Casi igual a la «e» española de «mesa», un poquito más abierta.',
    error: 'Confundirla con /æ/: «pen» (bolígrafo) y «pan» (sartén) son distintas.',
    pares: ['bed/bad', 'pen/pan', 'men/man', 'said/sad', 'bet/bat'] },
  { s: 'æ', g: 'vocal', nombre: 'a de «cat»', nivel: 3,
    ej: ['cat|kæt|a', 'apple|ˈæpəl|a', 'man|mæn|a', 'bad|bæd|a', 'black|blæk|a', 'happy|ˈhæpi|a'],
    grafias: 'a (cat, map, hand)',
    como: 'Mandíbula muy baja, labios estirados hacia los lados, lengua adelante y baja.',
    es: 'No existe en español. Es una mezcla entre «a» y «e»: abre la boca como para «a» y di «e».',
    error: 'Decir la «a» española: «hat» (sombrero) suena como «hot» (caliente) o «hut».',
    pares: ['cat/cut', 'hat/hot', 'bag/bug', 'cap/cup', 'bad/bed'] },
  { s: 'ɑ', g: 'vocal', nombre: 'a abierta (atrás)', nivel: 2,
    ej: ['hot|hɑt|o', 'father|ˈfɑðɚ|a', 'stop|stɑp|o', 'box|bɑks|o', 'car|kɑr|a', 'job|dʒɑb|o'],
    grafias: 'o (hot, stop), a (father, car)',
    como: 'Boca bien abierta, lengua baja y hacia atrás, labios relajados.',
    es: 'Parecida a la «a» española de «casa», pero más abierta y hacia atrás, como cuando el médico dice «di aaa».',
    error: 'Leer la «o» escrita como «o» española: «hot» se dice /hɑt/, no «jot».',
    pares: ['hot/hat', 'cop/cup', 'lock/luck', 'not/nut', 'hot/hut'] },
  { s: 'ɔ', g: 'vocal', nombre: 'o abierta', nivel: 2,
    ej: ['thought|θɔt|ough', 'law|lɔ|aw', 'dog|dɔɡ|o', 'walk|wɔk|a', 'call|kɔl|a', 'caught|kɔt|au'],
    grafias: 'aw, au, ough, a (walk, call), o (dog, long)',
    como: 'Boca abierta, labios un poco redondeados, lengua baja y atrás.',
    es: 'Como una «o» muy abierta. Nota: muchos estadounidenses la pronuncian igual que /ɑ/ («caught» = «cot»).',
    error: 'Cerrarla demasiado como la «o» española o como /oʊ/: «law» no es «low».',
    pares: ['law/low', 'bought/boat', 'caught/coat', 'walk/work', 'saw/so'] },
  { s: 'ʌ', g: 'vocal', nombre: 'a corta relajada (de «cup»)', nivel: 3,
    ej: ['cup|kʌp|u', 'sun|sʌn|u', 'love|lʌv|o', 'money|ˈmʌni|o', 'young|jʌŋ|ou', 'but|bʌt|u'],
    grafias: 'u (cup, sun), o (love, money), ou (young), oo (blood)',
    como: 'Boca medio abierta y relajada, lengua en el centro. Sonido corto, como un «ah» breve de sorpresa.',
    es: 'No existe en español. Suena como una «a» corta y floja, sin abrir mucho la boca.',
    error: 'Leer la «u» como «u» española: «cut» se dice /kʌt/, no «cut» con u.',
    pares: ['cup/cop', 'cut/cat', 'luck/lock', 'bug/bag', 'but/bat'] },
  { s: 'ə', g: 'vocal', nombre: 'schwa (vocal neutra)', nivel: 3,
    ej: ['about|əˈbaʊt|a', 'banana|bəˈnænə|a', 'sofa|ˈsoʊfə|a', 'problem|ˈprɑbləm|e', 'the|ðə|e', 'today|təˈdeɪ|o'],
    grafias: 'Cualquier vocal en sílaba sin acento: a, e, i, o, u',
    como: 'Boca y lengua totalmente relajadas, en el centro. Muy corta y débil.',
    es: 'No existe en español. Es la vocal MÁS común del inglés: aparece en casi todas las sílabas sin acento. Suena como un «ə» apagado, entre «a» y «e».',
    error: 'Pronunciar todas las vocales con fuerza, como en español: «banana» no es «ba-na-na» sino /bəˈnænə/.',
    pares: [] },
  { s: 'ʊ', g: 'vocal', nombre: 'u corta (relajada)', nivel: 3,
    ej: ['book|bʊk|oo', 'good|ɡʊd|oo', 'foot|fʊt|oo', 'put|pʊt|u', 'could|kʊd|ou', 'woman|ˈwʊmən|o'],
    grafias: 'oo (book), u (put, full), ou (could, would)',
    como: 'Labios poco redondeados, lengua relajada. Corta.',
    es: 'No existe en español. Es una «u» corta y floja, entre «u» y «o».',
    error: 'Decirla como la «u» larga española: «full» (lleno) suena como «fool» (tonto).',
    pares: ['full/fool', 'pull/pool', 'look/Luke', 'could/cooed'] },
  { s: 'u', g: 'vocal', nombre: 'u larga', nivel: 1,
    ej: ['food|fud|oo', 'blue|blu|ue', 'two|tu|wo', 'school|skul|oo', 'moon|mun|oo', 'do|du|o'],
    grafias: 'oo, u, ue, ew, o (do), ou (you)',
    como: 'Labios muy redondeados hacia adelante, lengua alta y atrás. Larga.',
    es: 'Como la «u» española de «luna», un poco más larga.',
    error: 'Hacerla corta: «pool» y «pull» deben sonar distintas.',
    pares: ['fool/full', 'pool/pull', 'Luke/look'] },
  { s: 'ɝ', g: 'vocal', nombre: 'vocal con R acentuada', nivel: 3,
    ej: ['bird|bɝd|ir', 'her|hɝ|er', 'word|wɝd|or', 'turn|tɝn|ur', 'first|fɝst|ir', 'learn|lɝn|ear'],
    grafias: 'er, ir, ur, or (word), ear (learn)',
    como: 'La lengua se recoge hacia atrás sin tocar el paladar, labios un poco redondeados. Suena la «r» y la vocal a la vez.',
    es: 'No existe en español. No digas «bird» como «bir-d»: la vocal y la r son un solo sonido continuo, «ɝɝɝ».',
    error: 'Poner una vocal española y luego una «r» vibrada.',
    pares: ['work/walk', 'bird/bud', 'hurt/hot', 'firm/farm'] },
  { s: 'ɚ', g: 'vocal', nombre: 'vocal con R sin acento', nivel: 3,
    ej: ['teacher|ˈtitʃɚ|er', 'water|ˈwɑtɚ|er', 'doctor|ˈdɑktɚ|or', 'color|ˈkʌlɚ|or', 'better|ˈbɛtɚ|er', 'dollar|ˈdɑlɚ|ar'],
    grafias: '-er, -or, -ar al final sin acento',
    como: 'Igual que /ɝ/ pero corta y débil, en sílabas sin acento.',
    es: 'No existe en español. «Teacher» termina en una «r» suave y larga, no en «-cher» con e.',
    error: 'Decir «tea-cher» con «e» española y «r» vibrada.',
    pares: [] },
  // ---------- Diptongos ----------
  { s: 'eɪ', g: 'diptongo', nombre: 'ei (de «day»)', nivel: 1,
    ej: ['day|deɪ|ay', 'name|neɪm|a', 'rain|reɪn|ai', 'great|ɡreɪt|ea', 'eight|eɪt|eigh', 'they|ðeɪ|ey'],
    grafias: 'a+consonante+e (name), ai, ay, ea (great), eigh, ey',
    como: 'Empieza en «e» y se desliza hacia «i».',
    es: 'Como «ei» en «rey» o «peine».',
    error: 'Decir solo «e»: «late» no es «let».',
    pares: ['late/let', 'wait/wet', 'sale/sell', 'pain/pen'] },
  { s: 'aɪ', g: 'diptongo', nombre: 'ai (de «my»)', nivel: 1,
    ej: ['my|maɪ|y', 'time|taɪm|i', 'night|naɪt|igh', 'fly|flaɪ|y', 'buy|baɪ|uy', 'eye|aɪ|eye'],
    grafias: 'i+consonante+e (time), y, igh, uy, eye',
    como: 'Empieza en una «a» abierta y se desliza hacia «i».',
    es: 'Como «ai» en «aire» o «hay».',
    error: 'Leer la «i» escrita como «i»: «time» se dice /taɪm/, no «tim».',
    pares: ['ice/eyes', 'price/prize', 'light/late'] },
  { s: 'ɔɪ', g: 'diptongo', nombre: 'oi (de «boy»)', nivel: 1,
    ej: ['boy|bɔɪ|oy', 'toy|tɔɪ|oy', 'coin|kɔɪn|oi', 'voice|vɔɪs|oi', 'enjoy|ɪnˈdʒɔɪ|oy', 'oil|ɔɪl|oi'],
    grafias: 'oy, oi',
    como: 'Empieza en una «o» abierta y se desliza hacia «i».',
    es: 'Como «oi» en «hoy» o «voy».',
    error: 'Casi no hay: ¡es fácil para hispanohablantes!',
    pares: [] },
  { s: 'aʊ', g: 'diptongo', nombre: 'au (de «now»)', nivel: 1,
    ej: ['now|naʊ|ow', 'house|haʊs|ou', 'out|aʊt|ou', 'brown|braʊn|ow', 'cow|kaʊ|ow', 'mouth|maʊθ|ou'],
    grafias: 'ou (house), ow (now)',
    como: 'Empieza en «a» y se desliza hacia «u».',
    es: 'Como «au» en «causa» o «auto».',
    error: 'Leer «ow» como «o»: «now» no es «no».',
    pares: ['now/no', 'town/tone', 'found/fund'] },
  { s: 'oʊ', g: 'diptongo', nombre: 'ou (de «go»)', nivel: 2,
    ej: ['go|ɡoʊ|o', 'home|hoʊm|o', 'boat|boʊt|oa', 'snow|snoʊ|ow', 'phone|foʊn|o', 'though|ðoʊ|ough'],
    grafias: 'o+consonante+e (home), oa, ow, o (go), ough (though)',
    como: 'Empieza en «o» y se desliza hacia «u», con los labios que se cierran un poco.',
    es: 'Parecida a la «o» española, pero termina en «u»: «gou», no «go».',
    error: 'Decir una «o» pura: suena muy extranjero y se confunde con /ɔ/.',
    pares: ['low/law', 'boat/bought', 'coat/caught', 'won\'t/want'] },
  // ---------- Vocales con R ----------
  { s: 'ɪr', g: 'vocal+r', nombre: 'ir (de «near»)', nivel: 2,
    ej: ['near|nɪr|ear', 'here|hɪr|ere', 'beer|bɪr|eer', 'year|jɪr|ear', 'clear|klɪr|ear', 'ear|ɪr|ear'],
    grafias: 'ear, eer, ere', como: 'Vocal /ɪ/ seguida de la r americana recogida.',
    es: 'Como «ir» pero con la r inglesa, sin vibrar.', error: 'Vibrar la r o decir «ní-ar».', pares: [] },
  { s: 'ɛr', g: 'vocal+r', nombre: 'er (de «hair»)', nivel: 2,
    ej: ['hair|hɛr|air', 'care|kɛr|are', 'where|wɛr|ere', 'bear|bɛr|ear', 'chair|tʃɛr|air', 'there|ðɛr|ere'],
    grafias: 'air, are, ear (bear), ere (where)', como: 'Vocal /ɛ/ seguida de la r americana.',
    es: 'Como «er» con la r inglesa.', error: 'Pronunciar «ai» en «hair» por la escritura.', pares: [] },
  { s: 'ɑr', g: 'vocal+r', nombre: 'ar (de «car»)', nivel: 2,
    ej: ['car|kɑr|ar', 'star|stɑr|ar', 'park|pɑrk|ar', 'heart|hɑrt|ear', 'far|fɑr|ar', 'art|ɑrt|ar'],
    grafias: 'ar, ear (heart)', como: 'Vocal /ɑ/ abierta seguida de la r americana.',
    es: 'Como «ar» con la r inglesa recogida.', error: 'Vibrar la r como en «carro».', pares: [] },
  { s: 'ɔr', g: 'vocal+r', nombre: 'or (de «door»)', nivel: 2,
    ej: ['door|dɔr|oor', 'more|mɔr|ore', 'four|fɔr|our', 'horse|hɔrs|or', 'north|nɔrθ|or', 'war|wɔr|ar'],
    grafias: 'or, ore, oor, our, ar (war)', como: 'Vocal /ɔ/ seguida de la r americana.',
    es: 'Como «or» con la r inglesa.', error: 'Decir «dur» por la escritura «oo».', pares: [] },
  { s: 'ʊr', g: 'vocal+r', nombre: 'ur (de «tour»)', nivel: 2,
    ej: ['tour|tʊr|our', 'sure|ʃʊr|ure', 'poor|pʊr|oor', 'cure|kjʊr|ure', 'pure|pjʊr|ure', 'your|jʊr|our'],
    grafias: 'our, ure, oor', como: 'Vocal /ʊ/ seguida de la r americana (muchos dicen /ɔr/).',
    es: 'Como «ur» con la r inglesa.', error: 'Vibrar la r.', pares: [] },
  { s: 'aɪr', g: 'vocal+r', nombre: 'air (de «fire»)', nivel: 2,
    ej: ['fire|faɪr|ire', 'tired|taɪrd|ire', 'wire|waɪr|ire', 'hire|haɪr|ire', 'choir|kwaɪr|oir', 'buyer|ˈbaɪɚ|uyer'],
    grafias: 'ire', como: 'Diptongo /aɪ/ seguido de la r americana.',
    es: 'Como «air» en español pero con la r inglesa.', error: 'Decir «fi-re» con dos sílabas marcadas.', pares: [] },
  // ---------- Consonantes ----------
  { s: 'p', g: 'consonante', nombre: 'p aspirada', nivel: 2, lugar: 'bilabial', modo: 'oclusiva', voz: false,
    ej: ['pen|pɛn|p', 'pie|paɪ|p', 'happy|ˈhæpi|pp', 'cup|kʌp|p', 'apple|ˈæpəl|pp', 'people|ˈpipəl|p'],
    grafias: 'p, pp', como: 'Labios cerrados que se abren con una explosión de aire.',
    es: 'Como la «p» española, pero al inicio de palabra sale un soplo de aire [pʰ]: pon la mano frente a la boca y siente el aire.',
    error: 'No soplar: la «p» sin aire suena como «b» para un oído americano.',
    pares: ['pig/big', 'pear/bear', 'pie/buy', 'cap/cab'] },
  { s: 'b', g: 'consonante', nombre: 'b', nivel: 2, lugar: 'bilabial', modo: 'oclusiva', voz: true,
    ej: ['bed|bɛd|b', 'baby|ˈbeɪbi|b', 'job|dʒɑb|b', 'rabbit|ˈræbɪt|bb', 'boy|bɔɪ|b', 'bus|bʌs|b'],
    grafias: 'b, bb', como: 'Labios cerrados, con vibración de la garganta.',
    es: 'Como la «b» de «bota». Entre vocales NO la suavices (en español «haba» suena suave).',
    error: 'Confundirla con /v/: en inglés «b» y «v» son sonidos distintos.',
    pares: ['berry/very', 'ban/van', 'best/vest', 'big/pig'] },
  { s: 't', g: 'consonante', nombre: 't aspirada', nivel: 2, lugar: 'alveolar', modo: 'oclusiva', voz: false,
    ej: ['ten|tɛn|t', 'time|taɪm|t', 'cat|kæt|t', 'table|ˈteɪbəl|t', 'stop|stɑp|t', 'two|tu|t'],
    grafias: 't, tt, ed (walked)', como: 'La punta de la lengua toca la encía detrás de los dientes (no los dientes), y sale aire.',
    es: 'Parecida a la «t» española, pero la lengua va más atrás (en la encía) y al inicio sale un soplo [tʰ]. Entre vocales suele sonar como una «r» suave: «water» ≈ «wara».',
    error: 'Poner la lengua en los dientes y no aspirar.',
    pares: ['ten/den', 'town/down', 'tree/three'] },
  { s: 'd', g: 'consonante', nombre: 'd', nivel: 2, lugar: 'alveolar', modo: 'oclusiva', voz: true,
    ej: ['dog|dɔɡ|d', 'day|deɪ|d', 'red|rɛd|d', 'daddy|ˈdædi|dd', 'door|dɔr|d', 'good|ɡʊd|d'],
    grafias: 'd, dd, ed (played)', como: 'Lengua en la encía detrás de los dientes, con vibración.',
    es: 'Como la «d» de «dedo» al inicio. No la suavices entre vocales ni al final: «red» termina en una «d» clara.',
    error: 'Suavizarla (como en «cada») y que suene /ð/: «day» no es «they».',
    pares: ['day/they', 'den/then', 'dough/though'] },
  { s: 'k', g: 'consonante', nombre: 'k aspirada', nivel: 1, lugar: 'velar', modo: 'oclusiva', voz: false,
    ej: ['key|ki|k', 'cat|kæt|c', 'back|bæk|ck', 'school|skul|ch', 'kind|kaɪnd|k', 'quick|kwɪk|qu'],
    grafias: 'k, c, ck, ch (school), qu', como: 'La parte de atrás de la lengua toca el paladar blando; sale un soplo al inicio.',
    es: 'Como la «c» de «casa» o «k», con un poco de aire al inicio [kʰ].',
    error: 'Casi no hay; solo recuerda el soplo.', pares: ['coat/goat', 'back/bag', 'cold/gold'] },
  { s: 'ɡ', g: 'consonante', nombre: 'g', nivel: 1, lugar: 'velar', modo: 'oclusiva', voz: true,
    ej: ['go|ɡoʊ|g', 'big|bɪɡ|g', 'bag|bæɡ|g', 'egg|ɛɡ|gg', 'girl|ɡɝl|g', 'give|ɡɪv|g'],
    grafias: 'g, gg, gu (guess)', como: 'Atrás de la lengua contra el paladar blando, con vibración.',
    es: 'Como la «g» de «gato», siempre fuerte, incluso antes de e/i en muchas palabras («give», «girl»).',
    error: 'Leer «g» antes de e/i como la «j» española.', pares: ['goat/coat', 'bag/back', 'gold/cold'] },
  { s: 'f', g: 'consonante', nombre: 'f', nivel: 1, lugar: 'labiodental', modo: 'fricativa', voz: false,
    ej: ['fish|fɪʃ|f', 'phone|foʊn|ph', 'laugh|læf|gh', 'coffee|ˈkɔfi|ff', 'five|faɪv|f', 'off|ɔf|ff'],
    grafias: 'f, ff, ph, gh (laugh)', como: 'Dientes de arriba sobre el labio inferior; sale aire sin vibración.',
    es: 'Igual que la «f» española.', error: 'Leer «ph» como «p».', pares: ['fan/van', 'fine/vine', 'fast/vast'] },
  { s: 'v', g: 'consonante', nombre: 'v (labiodental)', nivel: 3, lugar: 'labiodental', modo: 'fricativa', voz: true,
    ej: ['very|ˈvɛri|v', 'voice|vɔɪs|v', 'love|lʌv|v', 'seven|ˈsɛvən|v', 'have|hæv|v', 'van|væn|v'],
    grafias: 'v, f (of)', como: 'Como la /f/ (dientes arriba sobre el labio inferior) pero con vibración: debe zumbar.',
    es: 'En español «b» y «v» suenan igual, pero en inglés NO. Pon los dientes sobre el labio y haz vibrar la garganta.',
    error: 'Decir «b»: «very» suena como «berry» (baya).',
    pares: ['very/berry', 'van/ban', 'vest/best', 'vine/fine'] },
  { s: 'θ', g: 'consonante', nombre: 'th sorda (de «think»)', nivel: 2, lugar: 'dental', modo: 'fricativa', voz: false,
    ej: ['think|θɪŋk|th', 'three|θri|th', 'bath|bæθ|th', 'thank|θæŋk|th', 'mouth|maʊθ|th', 'birthday|ˈbɝθdeɪ|th'],
    grafias: 'th', como: 'La punta de la lengua entre los dientes; sopla aire sin vibración.',
    es: 'Es la «z» o «c» de España («zapato», «cena»). En Latinoamérica no existe: saca un poquito la lengua entre los dientes.',
    error: 'Decir «t» o «s»: «think» suena como «tink» o «sink» (fregadero).',
    pares: ['thin/sin', 'think/sink', 'three/tree', 'bath/bat', 'thank/tank'] },
  { s: 'ð', g: 'consonante', nombre: 'th sonora (de «this»)', nivel: 2, lugar: 'dental', modo: 'fricativa', voz: true,
    ej: ['this|ðɪs|th', 'the|ðə|th', 'mother|ˈmʌðɚ|th', 'they|ðeɪ|th', 'with|wɪð|th', 'brother|ˈbrʌðɚ|th'],
    grafias: 'th (en palabras como the, this, that, mother)', como: 'Lengua entre los dientes, con vibración.',
    es: 'Parecida a la «d» suave de «cada» o «nada», pero con la lengua entre los dientes.',
    error: 'Decir una «d» fuerte: «they» suena como «day».', pares: ['they/day', 'then/den', 'though/dough'] },
  { s: 's', g: 'consonante', nombre: 's', nivel: 1, lugar: 'alveolar', modo: 'fricativa', voz: false,
    ej: ['sun|sʌn|s', 'city|ˈsɪti|c', 'bus|bʌs|s', 'class|klæs|ss', 'school|skul|s', 'nice|naɪs|c'],
    grafias: 's, ss, c (city, nice)', como: 'Lengua cerca de la encía, aire que silba, sin vibración.',
    es: 'Igual que la «s» española. ¡Ojo! No pongas una «e» antes de s+consonante: «school», no «eschool».',
    error: 'Decir «espeak», «estudent».', pares: ['sue/zoo', 'bus/buzz', 'ice/eyes', 'sink/zinc'] },
  { s: 'z', g: 'consonante', nombre: 'z (s sonora)', nivel: 3, lugar: 'alveolar', modo: 'fricativa', voz: true,
    ej: ['zoo|zu|z', 'rose|roʊz|s', 'is|ɪz|s', 'dogs|dɔɡz|s', 'music|ˈmjuzɪk|s', 'easy|ˈizi|s'],
    grafias: 'z, zz, s (is, rose, dogs)', como: 'Como /s/ pero con vibración: un zumbido de abeja «zzzz».',
    es: 'No existe como sonido separado en español. Muchas «s» escritas en inglés suenan /z/ (is, has, was, dogs).',
    error: 'Decir «s»: «eyes» suena como «ice» (hielo).', pares: ['zoo/sue', 'buzz/bus', 'eyes/ice', 'prize/price'] },
  { s: 'ʃ', g: 'consonante', nombre: 'sh', nivel: 2, lugar: 'postalveolar', modo: 'fricativa', voz: false,
    ej: ['she|ʃi|sh', 'fish|fɪʃ|sh', 'nation|ˈneɪʃən|ti', 'shoe|ʃu|sh', 'sugar|ˈʃʊɡɚ|s', 'wash|wɑʃ|sh'],
    grafias: 'sh, ti (nation), ci (special), s (sugar)', como: 'Labios redondeados hacia adelante, lengua detrás de la encía, aire sin vibración.',
    es: 'Como el «shhh» para pedir silencio.', error: 'Decir «ch»: «ship» suena como «chip».',
    pares: ['sheep/cheap', 'ship/chip', 'shoe/chew', 'wash/watch'] },
  { s: 'ʒ', g: 'consonante', nombre: 'zh (de «vision»)', nivel: 2, lugar: 'postalveolar', modo: 'fricativa', voz: true,
    ej: ['vision|ˈvɪʒən|s', 'measure|ˈmɛʒɚ|s', 'usually|ˈjuʒuəli|s', 'television|ˈtɛləvɪʒən|s', 'garage|ɡəˈrɑʒ|g', 'beige|beɪʒ|g'],
    grafias: 's (vision), g (garage)', como: 'Como /ʃ/ pero con vibración.',
    es: 'Como la «ll/y» del español de Argentina y Uruguay: «yo», «calle».', error: 'Decir «s» o «ch».', pares: [] },
  { s: 'h', g: 'consonante', nombre: 'h aspirada', nivel: 2, lugar: 'glotal', modo: 'fricativa', voz: false,
    ej: ['hat|hæt|h', 'house|haʊs|h', 'who|hu|wh', 'happy|ˈhæpi|h', 'hello|həˈloʊ|h', 'behind|bɪˈhaɪnd|h'],
    grafias: 'h, wh (who)', como: 'Solo aire que sale de la garganta, como al empañar un vidrio.',
    es: 'Parecida a la «j» española, pero MUCHO más suave: sin raspar la garganta. Recuerda: en inglés la h SÍ suena (excepto hour, honest).',
    error: 'Omitirla («hat» → «at») o rasparla como «j» fuerte.', pares: ['hat/at', 'heat/eat', 'hold/old', 'hair/air'] },
  { s: 'tʃ', g: 'consonante', nombre: 'ch', nivel: 1, lugar: 'postalveolar', modo: 'africada', voz: false,
    ej: ['chair|tʃɛr|ch', 'cheap|tʃip|ch', 'watch|wɑtʃ|tch', 'teacher|ˈtitʃɚ|ch', 'kitchen|ˈkɪtʃən|tch', 'nature|ˈneɪtʃɚ|t'],
    grafias: 'ch, tch, t (nature, future)', como: 'Empieza como /t/ y termina como /ʃ/.',
    es: 'Igual que la «ch» española de «chocolate».', error: 'Casi no hay; cuidado con no confundirla con /ʃ/.',
    pares: ['cheap/sheep', 'chip/ship', 'chew/shoe', 'cheap/jeep'] },
  { s: 'dʒ', g: 'consonante', nombre: 'j inglesa (de «job»)', nivel: 2, lugar: 'postalveolar', modo: 'africada', voz: true,
    ej: ['job|dʒɑb|j', 'judge|dʒʌdʒ|j', 'age|eɪdʒ|g', 'orange|ˈɔrɪndʒ|g', 'jump|dʒʌmp|j', 'giant|ˈdʒaɪənt|g'],
    grafias: 'j, g (age, giant), dge (judge)', como: 'Como /tʃ/ pero con vibración.',
    es: 'Como la «y» enfática de «¡yo!» en muchos países («dyo»). NO es la «j» española.',
    error: 'Leer «j» como la «j» española: «job» no es «jaab».', pares: ['jet/yet', 'jeep/cheap', 'gin/chin', 'jello/yellow'] },
  { s: 'm', g: 'consonante', nombre: 'm', nivel: 1, lugar: 'bilabial', modo: 'nasal', voz: true,
    ej: ['man|mæn|m', 'summer|ˈsʌmɚ|mm', 'home|hoʊm|m', 'mom|mɑm|m', 'time|taɪm|m', 'come|kʌm|m'],
    grafias: 'm, mm', como: 'Labios cerrados, el aire sale por la nariz.', es: 'Igual que la «m» española.',
    error: 'Al final de palabra, ciérrala bien: «home», no «hon».', pares: [] },
  { s: 'n', g: 'consonante', nombre: 'n', nivel: 1, lugar: 'alveolar', modo: 'nasal', voz: true,
    ej: ['no|noʊ|n', 'sun|sʌn|n', 'ten|tɛn|n', 'dinner|ˈdɪnɚ|nn', 'know|noʊ|kn', 'nine|naɪn|n'],
    grafias: 'n, nn, kn (know)', como: 'Lengua en la encía, aire por la nariz.', es: 'Igual que la «n» española.',
    error: 'Pronunciar la «k» de «know».', pares: ['sin/sing', 'thin/thing', 'ran/rang'] },
  { s: 'ŋ', g: 'consonante', nombre: 'ng', nivel: 2, lugar: 'velar', modo: 'nasal', voz: true,
    ej: ['sing|sɪŋ|ng', 'long|lɔŋ|ng', 'thinking|ˈθɪŋkɪŋ|n', 'king|kɪŋ|ng', 'song|sɔŋ|ng', 'bank|bæŋk|n'],
    grafias: 'ng, n antes de k/g (bank, finger)', como: 'La parte de atrás de la lengua toca el paladar blando y el aire sale por la nariz.',
    es: 'Como la «n» de «tengo» o «banco». Al final de palabra NO pronuncies la «g»: «sing» = /sɪŋ/.',
    error: 'Decir «sin-g» o cambiarla por «n»: «thing» suena como «thin».', pares: ['sing/sin', 'thing/thin', 'rang/ran'] },
  { s: 'l', g: 'consonante', nombre: 'l (clara y oscura)', nivel: 2, lugar: 'alveolar', modo: 'lateral', voz: true,
    ej: ['leg|lɛɡ|l', 'hello|həˈloʊ|ll', 'feel|fil|l', 'milk|mɪlk|l', 'ball|bɔl|ll', 'little|ˈlɪtəl|l'],
    grafias: 'l, ll', como: 'Al inicio la lengua toca la encía (l clara). Al final se levanta también la parte de atrás de la lengua (l oscura [ɫ]).',
    es: 'Al inicio es como la «l» española. Al final de palabra suena más grave, casi como una «u»: «feel» ≈ «fiəl».',
    error: 'Hacer la «l» final igual que en español.', pares: ['light/right', 'lock/rock', 'load/road'] },
  { s: 'r', g: 'consonante', nombre: 'r americana', nivel: 3, lugar: 'postalveolar', modo: 'aproximante', voz: true, ipa2: 'ɹ',
    ej: ['red|rɛd|r', 'car|kɑr|r', 'very|ˈvɛri|r', 'right|raɪt|r', 'sorry|ˈsɑri|rr', 'three|θri|r'],
    grafias: 'r, rr, wr (write)', como: 'La lengua se recoge hacia atrás SIN tocar el paladar, los labios se redondean un poco. No vibra. (Símbolo técnico: /ɹ/.)',
    es: 'No existe en español. No hagas «r» vibrante ni la «r» suave de «pero». Imagina que dices una «u» con la lengua curvada hacia atrás.',
    error: 'Vibrarla: «red», «car» y «very» con r española suenan muy extranjeros.',
    pares: ['right/light', 'rock/lock', 'road/load', 'rice/lice'] },
  { s: 'w', g: 'consonante', nombre: 'w', nivel: 1, lugar: 'bilabial', modo: 'aproximante', voz: true,
    ej: ['we|wi|w', 'water|ˈwɑtɚ|w', 'one|wʌn|o', 'window|ˈwɪndoʊ|w', 'queen|kwin|u', 'what|wʌt|wh'],
    grafias: 'w, wh (what), u (queen), o (one)', como: 'Labios muy redondeados que se abren rápido.',
    es: 'Como la «u» rápida de «huevo» o «cuando».', error: 'Decir «gu» fuerte: «wood» no es «gud».', pares: ['west/vest', 'wine/vine', 'wet/vet'] },
  { s: 'j', g: 'consonante', nombre: 'y (semivocal)', nivel: 2, lugar: 'palatal', modo: 'aproximante', voz: true,
    ej: ['yes|jɛs|y', 'you|ju|y', 'yellow|ˈjɛloʊ|y', 'use|juz|u', 'music|ˈmjuzɪk|u', 'year|jɪr|y'],
    grafias: 'y, u (use, music)', como: 'La lengua se acerca al paladar sin tocarlo, suave.',
    es: 'Como la «i» de «hielo» o «ya» dicho suave. ¡Ojo! En el AFI el símbolo /j/ es el sonido «y», no la «j» española.',
    error: 'Decirla fuerte como «dʒ»: «yes» suena como «jes», «year» como «jeer».', pares: ['yet/jet', 'yellow/jello', 'year/ear'] }
];

// Sonidos especiales del inglés americano (alófonos y reglas)
const ESPECIALES = [
  { t: 'Flap T [ɾ]', icon: '🥁', desc: 'La t y la d entre vocales (con la segunda sin acento) suenan como la «r» suave española de «pero». Es la marca más típica del acento americano.',
    ej: ['water|ˈwɑɾɚ', 'better|ˈbɛɾɚ', 'city|ˈsɪɾi', 'little|ˈlɪɾəl', 'party|ˈpɑrɾi', 'get it|ˈɡɛɾɪt'] },
  { t: 'T glotal [ʔ]', icon: '✋', desc: 'Antes de «n» o al final de algunas palabras, la t se «corta» en la garganta, como la pausa de «uh-oh».',
    ej: ['button|ˈbʌʔn̩', 'mountain|ˈmaʊʔn̩', 'written|ˈrɪʔn̩', 'not now|nɑʔ naʊ'] },
  { t: 'Aspiración [pʰ tʰ kʰ]', icon: '💨', desc: 'P, t y k al inicio de una sílaba acentuada llevan un soplo de aire. Después de «s» no hay soplo.',
    ej: ['pin|pʰɪn', 'spin|spɪn', 'top|tʰɑp', 'stop|stɑp', 'cat|kʰæt', 'scan|skæn'] },
  { t: 'L oscura [ɫ]', icon: '🌑', desc: 'La l al final de sílaba se pronuncia con la parte de atrás de la lengua levantada, con un sonido grave.',
    ej: ['feel|fiɫ', 'milk|mɪɫk', 'ball|bɔɫ', 'school|skuɫ', 'people|ˈpipəɫ'] },
  { t: 'Terminación -ED', icon: '⏪', desc: 'El pasado regular -ed tiene 3 sonidos: /t/ después de sonidos sordos (p, k, s, ʃ, tʃ, f), /d/ después de sonidos sonoros y vocales, /ɪd/ después de t o d.',
    ej: ['walked|wɔkt', 'stopped|stɑpt', 'played|pleɪd', 'called|kɔld', 'wanted|ˈwɑntɪd', 'needed|ˈnidɪd'] },
  { t: 'Terminación -S', icon: '➕', desc: 'Plurales y tercera persona: /s/ después de sonidos sordos, /z/ después de sonoros y vocales, /ɪz/ después de s, z, ʃ, ʒ, tʃ, dʒ.',
    ej: ['cats|kæts', 'books|bʊks', 'dogs|dɔɡz', 'plays|pleɪz', 'buses|ˈbʌsɪz', 'watches|ˈwɑtʃɪz'] },
  { t: 'Formas débiles', icon: '🔉', desc: 'Las palabras pequeñas (to, and, can, for, of) casi siempre se pronuncian débiles, con schwa /ə/.',
    ej: ['to|tə', 'and|ən', 'can|kən', 'for|fɚ', 'of|əv', 'you|jə'] },
  { t: 'Acento de palabra', icon: '🎯', desc: 'La sílaba acentuada (marcada con ˈ) es más larga y fuerte; las demás se reducen. Cambiar el acento puede cambiar el significado.',
    ej: ['record (n.)|ˈrɛkɚd', 'record (v.)|rɪˈkɔrd', 'photograph|ˈfoʊɾəɡræf', 'photographer|fəˈtɑɡrəfɚ', 'present (n.)|ˈprɛzənt', 'present (v.)|prɪˈzɛnt'] },
  { t: 'Sin «e» antes de S', icon: '🚫', desc: 'El español añade una «e» antes de s + consonante. En inglés la palabra empieza directamente con la s.',
    ej: ['school|skul', 'speak|spik', 'student|ˈstudənt', 'Spain|speɪn', 'star|stɑr', 'sleep|slip'] },
  { t: 'Letras mudas', icon: '🤫', desc: 'Muchas letras escritas no se pronuncian.',
    ej: ['know|noʊ', 'write|raɪt', 'hour|aʊɚ', 'lamb|læm', 'listen|ˈlɪsən', 'Wednesday|ˈwɛnzdeɪ'] }
];

// Palabras extra para el diccionario y la práctica de transcripción
const EXTRA = [
  'hello|həˈloʊ', 'thank you|ˈθæŋk ju', 'please|pliz', 'sorry|ˈsɑri', 'goodbye|ɡʊdˈbaɪ', 'water|ˈwɑtɚ', 'coffee|ˈkɔfi', 'bread|brɛd',
  'chicken|ˈtʃɪkən', 'breakfast|ˈbrɛkfəst', 'family|ˈfæməli', 'mother|ˈmʌðɚ', 'father|ˈfɑðɚ', 'brother|ˈbrʌðɚ', 'sister|ˈsɪstɚ', 'friend|frɛnd',
  'house|haʊs', 'kitchen|ˈkɪtʃən', 'bedroom|ˈbɛdrum', 'window|ˈwɪndoʊ', 'computer|kəmˈpjutɚ', 'phone|foʊn', 'money|ˈmʌni', 'work|wɝk',
  'walk|wɔk', 'talk|tɔk', 'world|wɝld', 'word|wɝd', 'girl|ɡɝl', 'early|ˈɝli', 'Thursday|ˈθɝzdeɪ', 'thirty|ˈθɝɾi', 'thirteen|θɝˈtin',
  'enough|ɪˈnʌf', 'through|θru', 'thought|θɔt', 'although|ɔlˈðoʊ', 'comfortable|ˈkʌmftɚbəl', 'vegetable|ˈvɛdʒtəbəl', 'chocolate|ˈtʃɑklət',
  'interesting|ˈɪntrəstɪŋ', 'beautiful|ˈbjuɾəfəl', 'English|ˈɪŋɡlɪʃ', 'Spanish|ˈspænɪʃ', 'language|ˈlæŋɡwɪdʒ', 'pronunciation|prəˌnʌnsiˈeɪʃən',
  'question|ˈkwɛstʃən', 'answer|ˈænsɚ', 'because|bɪˈkʌz', 'people|ˈpipəl', 'favorite|ˈfeɪvərɪt', 'restaurant|ˈrɛstərɑnt', 'hospital|ˈhɑspɪɾəl',
  'doctor|ˈdɑktɚ', 'student|ˈstudənt', 'teacher|ˈtitʃɚ', 'university|ˌjunəˈvɝsəɾi', 'city|ˈsɪɾi', 'country|ˈkʌntri', 'weather|ˈwɛðɚ',
  'yesterday|ˈjɛstɚdeɪ', 'tomorrow|təˈmɑroʊ', 'morning|ˈmɔrnɪŋ', 'evening|ˈivnɪŋ', 'night|naɪt', 'year|jɪr', 'month|mʌnθ', 'clothes|kloʊz',
  'shirt|ʃɝt', 'shoes|ʃuz', 'jacket|ˈdʒækɪt', 'orange|ˈɔrɪndʒ', 'yellow|ˈjɛloʊ', 'purple|ˈpɝpəl', 'eleven|ɪˈlɛvən', 'twelve|twɛlv',
  'think|θɪŋk', 'there|ðɛr', 'their|ðɛr', 'they\'re|ðɛr', 'would|wʊd', 'wood|wʊd', 'right|raɪt', 'write|raɪt', 'hear|hɪr', 'here|hɪr',
  'buy|baɪ', 'by|baɪ', 'bye|baɪ', 'sea|si', 'see|si', 'knight|naɪt', 'hour|aʊɚ', 'our|aʊɚ', 'flower|ˈflaʊɚ', 'flour|ˈflaʊɚ'
];
